-- Bridge job types for local PDF parsing and SwimPhone meet import.
ALTER TYPE "BridgeJobType" ADD VALUE IF NOT EXISTS 'SWIMPHONE_MEET';
ALTER TYPE "BridgeJobType" ADD VALUE IF NOT EXISTS 'PARSE_MEET_PDF';
ALTER TYPE "BridgeJobType" ADD VALUE IF NOT EXISTS 'PARSE_MEET_SHEET';
ALTER TYPE "BridgeJobType" ADD VALUE IF NOT EXISTS 'PARSE_MEET_PACKET';
